/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShopModel } from './shopModel';


/**
 * attribute type model
 */
export interface AttributeTypeModel { 
    /**
     * identity attribute type
     */
    id?: string;
    /**
     * attibute type name
     */
    name?: string;
    /**
     * attribute type description
     */
    description?: string;
    shop?: ShopModel;
}

