/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShopModel } from './shopModel';


/**
 * category model
 */
export interface CategoryModel { 
    /**
     * category identity
     */
    id?: string;
    categoryParent?: CategoryModel;
    /**
     * name parent category
     */
    categoryParentName?: string;
    /**
     * category name
     */
    name?: string;
    /**
     * category description
     */
    description?: string;
    /**
     * is category parent
     */
    parent?: boolean;
    shop?: ShopModel;
}

