/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileModel } from './fileModel';
import { AttributeModel } from './attributeModel';
import { CategoryModel } from './categoryModel';
import { ShopModel } from './shopModel';


/**
 * product model
 */
export interface ProductModel { 
    /**
     * product identity
     */
    id?: string;
    category?: CategoryModel;
    /**
     * product name
     */
    name?: string;
    /**
     * product description
     */
    description?: string;
    /**
     * product characteristics
     */
    characteristics?: string;
    /**
     * product specifications
     */
    specifications?: string;
    /**
     * product code
     */
    code?: string;
    /**
     * part number
     */
    partNumber?: string;
    /**
     * product type code
     */
    typeCode?: string;
    price?: number;
    stock?: number;
    shop?: ShopModel;
    attributes?: Array<AttributeModel>;
    files?: Array<FileModel>;
}

