/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShopModel } from './shopModel';


/**
 * provider model
 */
export interface ProviderModel { 
    /**
     * identity provider
     */
    id?: string;
    /**
     * provider cif
     */
    cif?: string;
    /**
     * provider name
     */
    name?: string;
    /**
     * provider email
     */
    email?: string;
    /**
     * provider telephone
     */
    phone?: number;
    shop?: ShopModel;
}

