/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionModel } from './actionModel';


/**
 * rol model
 */
export interface RolModel { 
    /**
     * identificador del rol
     */
    id?: string;
    /**
     * nombre del rol
     */
    name?: string;
    /**
     * descripcion del rol
     */
    description?: string;
    actions?: Array<ActionModel>;
}

