export * from './frontShopAdminAction.service';
import { FrontShopAdminActionService } from './frontShopAdminAction.service';
export * from './frontShopAdminAttributeType.service';
import { FrontShopAdminAttributeTypeService } from './frontShopAdminAttributeType.service';
export * from './frontShopAdminCategory.service';
import { FrontShopAdminCategoryService } from './frontShopAdminCategory.service';
export * from './frontShopAdminProduct.service';
import { FrontShopAdminProductService } from './frontShopAdminProduct.service';
export * from './frontShopAdminProvider.service';
import { FrontShopAdminProviderService } from './frontShopAdminProvider.service';
export * from './frontShopAdminRol.service';
import { FrontShopAdminRolService } from './frontShopAdminRol.service';
export * from './frontShopAdminShop.service';
import { FrontShopAdminShopService } from './frontShopAdminShop.service';
export * from './frontShopAdminUser.service';
import { FrontShopAdminUserService } from './frontShopAdminUser.service';
export * from './shopProductEntranceProductStock.service';
import { ShopProductEntranceProductStockService } from './shopProductEntranceProductStock.service';
export const APIS = [FrontShopAdminActionService, FrontShopAdminAttributeTypeService, FrontShopAdminCategoryService, FrontShopAdminProductService, FrontShopAdminProviderService, FrontShopAdminRolService, FrontShopAdminShopService, FrontShopAdminUserService, ShopProductEntranceProductStockService];
