/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * action model
 */
export interface ActionModel { 
    /**
     * action identity
     */
    id?: string;
    /**
     * action name
     */
    name?: string;
    /**
     * action description
     */
    description?: string;
}

