/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeTypeModel } from './attributeTypeModel';


/**
 * attribute model
 */
export interface AttributeModel { 
    /**
     * attribute identity
     */
    id?: string;
    attributeType?: AttributeTypeModel;
    /**
     * attribute description
     */
    value?: string;
}

