/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryModel } from './categoryModel';


/**
 * category pageable request
 */
export interface CategoryPageableRequest { 
    categories?: Array<CategoryModel>;
}

