/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * respuesta comun
 */
export interface OperationOutcome { 
    /**
     * identificador de la respuesta
     */
    codigo?: number;
    /**
     * descripción de la respuesta
     */
    descripcion?: string;
    /**
     * servicio queda la respuesta
     */
    servicio?: string;
}

