/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductModel } from './productModel';


/**
 * product pageable request
 */
export interface ProductPageableRequest { 
    products?: Array<ProductModel>;
    page?: number;
    totalPages?: number;
    numberResult?: number;
    totalResult?: number;
}

