/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * shop model
 */
export interface ShopModel { 
    /**
     * shop identity
     */
    id?: string;
    /**
     * shop name
     */
    name?: string;
    /**
     * shop description
     */
    description?: string;
    /**
     * url shop
     */
    url?: string;
    /**
     * is online the shop
     */
    online?: boolean;
    /**
     * system of the shop
     */
    system?: string;
    /**
     * start date of the shop
     */
    startDate?: string;
}

