/**
 * API SHOP
 * Servicio de ft shop admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolModel } from './rolModel';
import { ShopModel } from './shopModel';


/**
 * user model
 */
export interface UserModel { 
    /**
     * identificador del usuario
     */
    id?: string;
    /**
     * nombre del usuario
     */
    name?: string;
    /**
     * email del usuario
     */
    email?: string;
    /**
     * password del usuario
     */
    password?: string;
    roles?: Array<RolModel>;
    shops?: Array<ShopModel>;
}

